### ISSUE TITLE
Purpose of the Executor class

### ISSUE THREAD

**Issue by davidkraus** [AppCron/ACInteractor#23]
Hey,

can you give me some insight on what the purpose of the Executor class is?
What's stopping me to just inject an Interactor into a ViewController and call the execute function myself.

**Comment by florieger** [comment]
Some Interactors might have a complex initializer with several dependencies / plugins. These plugins sometimes have their own dependencies, that need to be provided in their initializers.

A simple variant is shown at https://github.com/AppCron/ACInteractor#dependency-injection, but in practice this can be more complex.

The ViewController should know nothing about these dependencies, thus it should not have to create a Interactor on its own. Additional this would be necessary for each ViewController using the same Interactor producing duplicate code.

Easy Unit testing is another advantage of the Executor. The entire Interactor setup with all the dependencies can be easily tested.

You mentioned that you want to inject the Interactor to the ViewController. This would work, but I wonder where the Interactor is initialized instead. If one ViewController creates another ViewController, e.g. to push it on the NavigationController, you would end up with the issues described above.

I hope this helps.
